### ISSUE TITLE
Ability to use sandbox

### ISSUE THREAD

**Issue by kaptk2** [dnsimple/dnsimple-php#2]
It would be nice if there was a simple way to use the sandbox api

**Comment by onlyhavecans** [comment]
When you construct the Client and pass in the config array you should be able to set `client_uri` to "https://api.sandbox.dnsimple.com/" to access the sandbox. Can you please try this? If that is not working it us a bug we will need to check into

https://github.com/dnsimple/dnsimple-php/blob/e0fbfb8e4e63f509b94ef9571e213e0d117ff9f8/src/Dnsimple/Client.php#L127-L138

**Comment by kaptk2** [comment]
I was misreading the code:
$client = new Client("API KEY", ['base_uri' => "https://api.sandbox.dnsimple.com/"]);

works great, sorry for the noise.
