### ISSUE TITLE
Package `phpunit/php-token-stream` is abandoned

### ISSUE THREAD

**Issue by dallasread** [dnsimple/dnsimple-php#5]
Upon installation, I received this error:

```
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
```

We should find an alternative.

**Comment by weppos** [comment]
I don't think we use it directly, the only dependency I see is `phpunit/phpunit`. Perhaps upgrading to `phpunit/phpunit` 9x may solve the issue.

**Comment by deanlj** [comment]
A bump to phpunit 9 will remove the warning, 
https://github.com/laravel/ui/issues/134#issuecomment-676385024

however that forces a bump to PHP 7.3

I'm assuming guzzle 6.5 works fine with PHP 7.3 so may not be an issue but may prompt whether to drop support for Guzzle 6.5.  I don't have a guzzle 6.5 app to confirm or not.
